require "patience_diff"
require "diff-lcs"

require_relative "super_diff/csi"
require_relative "super_diff/errors"
require_relative "super_diff/helpers"
require_relative "super_diff/value_inspection"

require_relative "super_diff/object_inspection"
require_relative "super_diff/object_inspection/nodes"
require_relative "super_diff/object_inspection/nodes/base"
require_relative "super_diff/object_inspection/nodes/break"
require_relative "super_diff/object_inspection/nodes/inspection"
require_relative "super_diff/object_inspection/nodes/nesting"
require_relative "super_diff/object_inspection/nodes/text"
require_relative "super_diff/object_inspection/nodes/when_multiline"
require_relative "super_diff/object_inspection/inspection_tree_evaluator"
require_relative "super_diff/object_inspection/inspection_tree"
require_relative "super_diff/object_inspection/inspectors"
require_relative "super_diff/object_inspection/inspectors/array"
require_relative "super_diff/object_inspection/inspectors/custom_object"
require_relative "super_diff/object_inspection/inspectors/default_object"
require_relative "super_diff/object_inspection/inspectors/hash"
require_relative "super_diff/object_inspection/inspectors/primitive"
require_relative "super_diff/object_inspection/inspectors/string"

require_relative "super_diff/equality_matchers/base"
require_relative "super_diff/equality_matchers/array"
require_relative "super_diff/equality_matchers/hash"
require_relative "super_diff/equality_matchers/multi_line_string"
require_relative "super_diff/equality_matchers/single_line_string"
require_relative "super_diff/equality_matchers/object"
require_relative "super_diff/equality_matchers"
require_relative "super_diff/equality_matcher"

require_relative "super_diff/operations/unary_operation"
require_relative "super_diff/operations/binary_operation"

require_relative "super_diff/operation_sequences/base"
require_relative "super_diff/operation_sequences/array"
require_relative "super_diff/operation_sequences/hash"
require_relative "super_diff/operation_sequences/object"

require_relative "super_diff/operational_sequencers/base"
require_relative "super_diff/operational_sequencers/array"
require_relative "super_diff/operational_sequencers/hash"
require_relative "super_diff/operational_sequencers/multi_line_string"
require_relative "super_diff/operational_sequencers/object"
require_relative "super_diff/operational_sequencers"
require_relative "super_diff/operational_sequencer"

require_relative "super_diff/diff_formatters/collection"
require_relative "super_diff/diff_formatters/base"
require_relative "super_diff/diff_formatters/array"
require_relative "super_diff/diff_formatters/hash"
require_relative "super_diff/diff_formatters/multi_line_string"
require_relative "super_diff/diff_formatters/object"
require_relative "super_diff/diff_formatters"
require_relative "super_diff/diff_formatter"

require_relative "super_diff/differs/base"
require_relative "super_diff/differs/array"
require_relative "super_diff/differs/empty"
require_relative "super_diff/differs/hash"
require_relative "super_diff/differs/multi_line_string"
require_relative "super_diff/differs/object"
require_relative "super_diff/differs"
require_relative "super_diff/differ"
