#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# If the push refs start with (delete), then we're deleting a branch, so skip the pre-push hook
# Source: <https://github.com/typicode/husky/issues/169#issuecomment-1719263454>
stdin="$(cat -)"
if echo "$stdin" | grep -q "^(delete)"; then
  exit 0
fi

current_branch_name="$(git branch --show-current)"

if [[ "$current_branch_name" == "main" ]]; then
  raw_files_to_check="$(git diff origin/main...HEAD --name-only --diff-filter=d)"
else
  raw_files_to_check="$(git diff main...HEAD --name-only --diff-filter=d)"
fi

if [[ -n "$raw_files_to_check" ]]; then
  echo "*** Checking for lint violations in changed files ***************"
  echo

  echo "$raw_files_to_check" | while IFS='\n' read -r line; do
    printf '%s\0' "$line"
  done | xargs -0 yarn prettier --check --ignore-unknown || exit $?
fi

echo
echo "*** Auditing dependencies ***************"
echo

yarn audit || exit $?

echo
