#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo "*** Checking for lint violations in changed files ***************"
echo

yarn prettier --check --ignore-unknown $(git diff --cached "$(git merge-base main HEAD)" --name-only --diff-filter=d) || exit $?

echo
echo "*** Auditing dependencies ***************"
echo

yarn audit || exit $?

echo
